package com.reimagineafrica.notification.enums;

public enum NotificationEvent {
    MEMBER_CREATED,
    MEMBER_ACTIVATED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_DISBURSED,
    CONTRIBUTION_MISSED,
    GUARANTOR_CONSENT_REQUESTED,
    DIVIDEND_DECLARED,
    OTP_VERIFICATION,
    LOAN_REPAYMENT_REMINDER,
    CONTRIBUTION_DEPOSITED,
    CONTRIBUTION_WITHDRAWN
}
